version: '3.5'

services:
  db_reserve:
    container_name: db_templates_postgres_container
    ports:
      - "5536:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
      - POSTGRES_DB=db_templates
      - PGDATA=/data/postgres
    image: postgres
    restart: unless-stopped


