spring:
  application:
    name: senla-sender-of-messages

  datasource:
    url: jdbc:postgresql://localhost:5536/db_templates
    username: admin
    password: root
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: changelogs/changelog.xml
    enabled: true

  jpa:
    show-sql: false

  kafka:
    consumer:
      bootstrap:
        servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: payment-created-event
      properties:
        spring:
          json:
            trusted:
              packages: "*"

  mail:
    protocol: smtps
    host: smtp.yandex.ru
    port: 465
    username: kom4rolha@yandex.by
    password: Ro11092008
    test-connection: false
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  freemarker:
    template-loader-path: classpath:/templates/
    charset: UTF-8

server:
  port: 8888


